# 应用名称
spring:
  application:
    name: sharding-jdbc-demo
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    #读写分离
#    url: jdbc:shardingsphere:classpath:shardingsphere-readwrite.yaml
    #垂直分片
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding.yaml
    #水平分片-分库
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding2.yaml
    #水平分片-分表
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding3.yaml
    #水平分片-分库分表
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding4.yaml
    #自动分片算法-取模分片算法
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding5.yaml
    #自动分片算法-哈希取模分片算法
#    url: jdbc:shardingsphere:classpath:shardingsphere-sharding6.yaml
    #分片-多表关联
    url: jdbc:shardingsphere:classpath:shardingsphere-sharding7.yaml
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /


